a4_u_form_homepage:
    path: /
    defaults: { _controller: A4UFormBundle:Page:index }


a4_u_form_hello:
    path:     /form/porte_aperte_estate
    defaults: { _controller: A4UFormBundle:Page:porte_aperte_estate }

random:
    path:     /random/{limit}
    defaults: { _controller: A4UFormBundle:Random:index }
