a4_u_form_homepage:
    path: /
    defaults: { _controller: A4UFormBundle:Page:index }


a4_u_form_porteAperteEstate:
    path:     /form/porte_aperte_estate
    defaults: { _controller: A4UFormBundle:Page:porte_aperte_estate }

a4_u_form_success:
    path:	/form/success
    defaults: { _controller: A4UFormBundle:Page:success }