a4u_form_homepage:
    path: /
    defaults: { _controller: A4UFormBundle:Page:index }


a4u_form_porteAperteEstate:
    path:     /form/porte_aperte_estate
    defaults: { _controller: A4UFormBundle:Page:porte_aperte_estate }

a4u_form_showPAE:
    path: /admin/form/show_pae
    defaults: { _controller: A4UFormBundle:Page:showPAE }

a4u_form_searchPAE:
    path: /admin/form/search_pae
    defaults: { _controller: A4UFormBundle:Form:searchPAE }


a4u_form_porteAperteInverno:
    path:     /form/porte_aperte_inverno
    defaults: { _controller: A4UFormBundle:Page:porte_aperte_inverno }

a4u_form_showPAI:
    path: /admin/form/show_pai
    defaults: { _controller: A4UFormBundle:Page:showPAI }

a4u_form_searchPAI:
    path: /admin/form/search_pai
    defaults: { _controller: A4UFormBundle:Form:searchPAI }


a4u_form_stage:
    path:   /form/stage
    defaults: { _controller: A4UFormBundle:Page:stage }

a4u_form_showStage:
    path:   /admin/form/show_stage
    defaults: { _controller: A4UFormBundle:Page:showstage }

a4u_form_searchPAI:
    path: /admin/form/search_stage
    defaults: { _controller: A4UFormBundle:Form:searchStage }



a4u_form_generico:
    path:   /form/generico
    defaults: { _controller: A4UFormBundle:Page:generico }

a4u_form_showGenerico:
    path:   /admin/form/show_generico
    defaults: { _controller: A4UFormBundle:Page:showgenerico }

a4u_form_searchGenerico:
    path: /admin/form/search_generico
    defaults: { _controller: A4UFormBundle:Form:searchGenerico }





a4u_form_provaHera:
    path:   /prova/showhera
    defaults:   { _controller: A4UFormBundle:Page:show_Hera }
