services:
    A4U_Form.form.type.porteAperteEstate:
        class: A4U\FormBundle\Form\Type\PorteAperteEstateType
        tags:
            - { name: form.type, alias: porteAperteEstate }

    A4U_Form.form.type.porteAperteInverno:
        class: A4U\FormBundle\Form\Type\PorteAperteInvernoType
        tags:
            - { name: form.type, alias: porteAperteInverno }

    A4U_Form.form.type.stage:
        class: A4U\FormBundle\Form\Type\StageType
        tags:
            - { name: form.type, alias: stage }

    A4U_Form.form.type.generico:
        class: A4U\FormBundle\Form\Type\GenericoType
        tags:
            - { name: form.type, alias: generico }

#    a4_u_form.example:
#        class: A4U\FormBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
