services:
    A4U_Form.form.type.porteAperteEstate:
        class: A4U\FormBundle\Form\Type\PorteAperteEstateType
        tags:
            - { name: form.type, alias: porteAperteEstate }

            
#    a4_u_form.example:
#        class: A4U\FormBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
