#Validazione lato server, viene invocato ogni volta tramite il metodo isValid()

A4U\FormBundle\Entity\PorteAperteEstate:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: fiscalcode
            message: 'Il codice fiscale inserito è già presente nei nostri Database'

    properties:
        name:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        address:
        cap:
        city:
        email:
            - Email:
                message: The email {{ value }} is not a valid email.
                checkMX: true
        phone:
        birthDate:
        birthPlace:
        attendedSchool:
        hasAttendedToOtherActivities:
            - Choice:
                choices: [1, 0]
        activity:
        otherActivity:
        reference:
        otherReference:
        unicamCourse:
        fiscalcode:



A4U\FormBundle\Entity\PorteAperteInverno:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: fiscalcode
            message: 'Il codice fiscale inserito è già presente nei nostri Database'

    properties:
        name:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        address:
        cap:
        city:
        email:
            - Email:
                message: The email {{ value }} is not a valid email.
                checkMX: true
        phone:
        birthDate:
        birthPlace:
        attendedSchool:
        hasAttendedToOtherActivities:
            - Choice:
                choices: [1, 0]
        activity:
        otherActivity:
        reference:
        otherReference:
        unicamCourse:
        fiscalcode:



A4U\FormBundle\Entity\Stage:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: fiscalcode
            message: 'Il codice fiscale inserito è già presente nei nostri Database'
    properties:
        name:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        birthPlace:
        birthDate:
        address:
        cap:
        city:
        fiscalcode:
        attendedSchool:
        schoolYear:
            - Type:
                type: integer
                message: Il valore {{ value }} non è un {{ type }} valido.
        email:
        phone:
        facebookContact:
        stagePeriod:
        firstStudyField:
        secondStudyField:
        firstChoice:
        secondChoice:
        moneyPayed:



A4U\FormBundle\Entity\Generico:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: fiscalcode
            message: 'Il codice fiscale inserito è già presente nei nostri Database'
    properties:
        name:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        address:
            - NotBlank: ~
        cap:
            - NotBlank: ~
        city:
            - NotBlank: ~
        email:
            - Email:
                message: The email {{ value }} is not a valid email.
                checkMX: true
        birthDate:
            - NotBlank: ~
        birthPlace:
            - NotBlank: ~
        attendedActivity:
            - NotBlank: ~
        fiscalcode:
            - NotBlank: ~

