a4_u_data:
    resource: "@A4UDataBundle/Resources/config/routing.php"
    prefix:   /

a4_u_esse3:
    resource: "@A4UEsse3Bundle/Resources/config/routing.yml"
    prefix:   /

a4_u_user:
    resource: "@A4UUserBundle/Resources/config/routing.yml"
    prefix:   /

a4_u_form:
    resource: "@A4UFormBundle/Resources/config/routing.yml"
    prefix:   /
