security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            http_basic:
                realm: "Area demo protetta"
            form_login: ~
            remember_me:
                key:      "%secret%"
                lifetime: 86400 # 365 giorni in secondi
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            
            logout: ~



    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        # Includere anche la riga seguente per proteggere il percorso /admin
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext