<?php

namespace A4U\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StageTypeRepository extends EntityRepository
{

    /**
     * Get Choices
     * @param string|null
     * @return array 
     */
    public function getChoices($studyField, $stagePeriod)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s0')
        ->from('A4UDataBundle:StageType', 's0')
        ->where('s0.campoStudio = :studyField')
        ->andWhere('s0.dataInizioDataFine = :stagePeriod')
        ->setParameters(array(
            'studyField' => ($studyField),
            'stagePeriod' => ($stagePeriod)
        ));

        return $qb;
    }
}
