<?php

namespace A4U\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StuAnagScuoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuAnagScuoleRepository extends EntityRepository
{
    /**
     * Get Regioni
     *
     * @return array 
     */
    public function getRegioni()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.regione != :blank')
        ->groupBy('s0.regione')
        ->setParameters(array(
            'blank' => (' ')
        ));

        return $qb;
    }

    /**
     * Get Provincie
     * @param StuAnagScuole|null
     * @return array 
     */
    public function getProvincie(StuAnagScuole $scuola)
    {
        
        $regione = $scuola->getRegione();

        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.regione = :regione')
        ->groupBy('s0.provincia')
        ->setParameters(array(
            'regione' => ($regione)
        ));

        return $qb;
    }    

    /**
     * Get Provincie
     * @param string|null
     * @return array 
     */
    public function getProvincieStringa($scuola)
    {
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0.regione')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.idRecord = :scuola')
        ->setParameters(array(
            'scuola' => ($scuola)
        ));
        $query = $qb->getQuery();
        $regione = $query->getResult();
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.regione = :regione')
        ->groupBy('s0.provincia')
        ->setParameters(array(
            'regione' => ($regione)
        ));

        return $qb;
    }    

    /**
     * Get Citta
     * @param StuAnagScuole
     * @return array 
     */
    public function getCitta(StuAnagScuole $scuola)
    {
        
        $provincia = $scuola->getProvincia();

        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.provincia = :provincia')
        ->groupBy('s0.citta')
        ->setParameters(array(
            'provincia' => ($provincia)
        ));

        return $qb;
    }

    /**
     * Get Citta
     * @param string|null
     * @return array 
     */
    public function getCittaStringa($scuola)
    {
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0.provincia')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.idRecord = :scuola')
        ->setParameters(array(
            'scuola' => ($scuola)
        ));
        $query = $qb->getQuery();
        $provincia = $query->getResult();
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.provincia = :provincia')
        ->groupBy('s0.citta')
        ->setParameters(array(
            'provincia' => ($provincia)
        ));

        return $qb;
    }

    /**
     * Get School
     * @param StuAnagScuole
     * @return array 
     */
    public function getSchool(StuAnagScuole $scuola)
    {
    	
        $citta = $scuola->getCitta();

        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.citta = :citta')
        ->setParameters(array(
            'citta' => ($citta)
        ));

        return $qb;
    }

    /*
     * Get School
     * @param string|null
     * @return array 
     */
    public function getSchoolString($scuola)
    {
    	
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('s0.citta')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.idRecord = :scuola')
        ->setParameters(array(
            'scuola' => ($scuola)
        ));
        $query = $qb->getQuery();
        $citta = $query->getResult();
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s0')
        ->from('A4UDataBundle:StuAnagScuole', 's0')
        ->where('s0.citta = :citta')
        ->orderBy('s0.Tipologia','ASC')
        ->setParameters(array(
            'citta' => ($citta)
        ));

        return $qb;
    }

}
