<?php

namespace A4U\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StuAnagScuoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuAnagScuoleRepository extends EntityRepository
{
    /**
     * Get Regioni
     *
     * @return array 
     */
    public function getRegioni()
    {
    	$qb = $this->getEntityManager()->createQueryBuilder();

        $regioni = $qb->select('s0_.Regione AS regione0')
           ->distinct()
           ->from('StuAnagScuole', 's0_');

        #$regioni = $query->getResult();

        return $regioni;
    }
}
