<?php

namespace A4U\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StuAnagScuoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuAnagScuoleRepository extends EntityRepository
{
    /**
     * Get Regioni
     *
     * @return array 
     */
    public function getRegioni()
    {
    	$this->getEntityManager()
    		->createQueryBuilder('r')
            ->select('r.Regione')->distinct()
            ->getQuery();

        $regioni = $query->getResult();

        return $regioni;
    }
}
